### ISSUE TITLE
Intro - testing features in "Issues" section

### ISSUE THREAD

**Issue by armin-es** [armin-es/form-auto-complete-javascript#1]
### Purpose of the project:

The project is a small JavaScript code written for HTML forms to duplicate text input values.
#### Referencing cross-repository Issues:

As an example: armin-es/image-gallery-javaScript-1#2

@alireza-saberi: I've added you as a collaborator for this repository.

**Comment by alireza-saberi** [comment]
Collaboration is accepted 
/cc @armin-es
