### ISSUE TITLE
Form attributes are missing

### ISSUE THREAD

**Issue by alireza-saberi** [armin-es/form-auto-complete-javascript#3]
## Bug Description

forms are required to have `method` and `action` attributes
check out the [w3school for more information](http://www.w3schools.com/tags/tag_form.asp)
## Steps to Reproduce

See line 18th in the index.html
## Expected Behavior

form tag should be something like `<form action="demo_form.asp" method="get">`

**Comment by armin-es** [comment]
@alireza-saberi : 
as this little project is focused on adding interactivity to front-end web (no back-end at the moment), `action` and `method` attributes of the `form` element are ignored.
