### ISSUE TITLE
Page icon is missing

### ISSUE THREAD

**Issue by alireza-saberi** [armin-es/form-auto-complete-javascript#4]
## Bug Description

Page is missing icon
## Actual Behavior

There is no link tag for page icon
## Expected Behavior

`<link rel="icon" href='xyz'>` is expected in the head

**Comment by armin-es** [comment]
I forgot to mention this issue number in my commits I did for the favicon.

I added the icon to html with the last 4 commits:
- 59ffa84858a6a32402c76dd5917e9a265bab2021
- 9003ed59ac7411349d42b5f34b6768674b951d81
- 7a7688ec9df8047dd7cd774099d5f65d03836275
- ccfe51f679e3498f5386e13ee91c12b3658e8d97

/cc @alireza-saberi
