### ISSUE TITLE
jsdoc 

### ISSUE THREAD

**Issue by alireza-saberi** [armin-es/form-auto-complete-javascript#8]
To have more pro like project since the project has JS aspects., we can follow up [Udacity nanodegree  styleguide for JSDoc.js](https://udacity.github.io/git-styleguide/) at the last part of project

I already added `jsdoc` as a dependency to the project.

**Comment by armin-es** [comment]
Excited to use `jsdoc` in my projects from now on. :sparkles: :clap:

**Comment by alireza-saberi** [comment]
I found the solution, the comment should be outside and on the top of the function declaration :eyeglasses:.
